<li><a href="javascript:;"><img src="/images/prod/kt/<?php echo $prodSn ;?>/p1.jpg" alt=""></a></li>
<li><a href="javascript:;"><img src="/images/prod/kt/<?php echo $prodSn ;?>/p2.jpg" alt=""></a></li>
<li><a href="javascript:;"><img src="/images/prod/kt/<?php echo $prodSn ;?>/p3.jpg" alt=""></a></li>
<li><a href="javascript:;"><img src="/images/prod/kt/<?php echo $prodSn ;?>/p4.jpg" alt=""></a></li>
<li><a href="javascript:;"><img src="/images/prod/kt/<?php echo $prodSn ;?>/p5.jpg" alt=""></a></li>
<li><a href="javascript:;"><img src="/images/prod/kt/<?php echo $prodSn ;?>/p6.jpg" alt=""></a></li>