<li><a href="javascript:;"><img src="/images/prod/cm/<?php echo $prodCode ;?>/p1.jpg" alt=""></a></li>
<li><a href="javascript:;"><img src="/images/prod/cm/<?php echo $prodCode ;?>/p2.jpg" alt=""></a></li>
<li><a href="javascript:;"><img src="/images/prod/cm/<?php echo $prodCode ;?>/p3.jpg" alt=""></a></li>
<li><a href="javascript:;"><img src="/images/prod/cm/<?php echo $prodCode ;?>/p4.jpg" alt=""></a></li>
<li><a href="javascript:;"><img src="/images/prod/cm/<?php echo $prodCode ;?>/p5.jpg" alt=""></a></li>
